language: node_js
node_js: 11
sudo: true
install:
  - yarn install
script:
  - make build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: .vuepress/dist
  github_token: $GITHUB_TOKEN # Set in the Travis settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: master
